# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

import backend_pb2 as backend__pb2


class ChatServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.addMessageEvent = channel.unary_unary(
                '/chat.ChatService/addMessageEvent',
                request_serializer=backend__pb2.MessageEvent.SerializeToString,
                response_deserializer=backend__pb2.EmptyResponse.FromString,
                )
        self.getMessageEvent = channel.unary_stream(
                '/chat.ChatService/getMessageEvent',
                request_serializer=backend__pb2.GetMessageRequest.SerializeToString,
                response_deserializer=backend__pb2.MessageEvent.FromString,
                )
        self.deleteMessageEvent = channel.unary_unary(
                '/chat.ChatService/deleteMessageEvent',
                request_serializer=backend__pb2.MessageEvent.SerializeToString,
                response_deserializer=backend__pb2.EmptyResponse.FromString,
                )
        self.notifyNewMessage = channel.unary_unary(
                '/chat.ChatService/notifyNewMessage',
                request_serializer=backend__pb2.NotifyEvent.SerializeToString,
                response_deserializer=backend__pb2.EmptyResponse.FromString,
                )


class ChatServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def addMessageEvent(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def getMessageEvent(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def deleteMessageEvent(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def notifyNewMessage(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_ChatServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'addMessageEvent': grpc.unary_unary_rpc_method_handler(
                    servicer.addMessageEvent,
                    request_deserializer=backend__pb2.MessageEvent.FromString,
                    response_serializer=backend__pb2.EmptyResponse.SerializeToString,
            ),
            'getMessageEvent': grpc.unary_stream_rpc_method_handler(
                    servicer.getMessageEvent,
                    request_deserializer=backend__pb2.GetMessageRequest.FromString,
                    response_serializer=backend__pb2.MessageEvent.SerializeToString,
            ),
            'deleteMessageEvent': grpc.unary_unary_rpc_method_handler(
                    servicer.deleteMessageEvent,
                    request_deserializer=backend__pb2.MessageEvent.FromString,
                    response_serializer=backend__pb2.EmptyResponse.SerializeToString,
            ),
            'notifyNewMessage': grpc.unary_unary_rpc_method_handler(
                    servicer.notifyNewMessage,
                    request_deserializer=backend__pb2.NotifyEvent.FromString,
                    response_serializer=backend__pb2.EmptyResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'chat.ChatService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class ChatService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def addMessageEvent(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/chat.ChatService/addMessageEvent',
            backend__pb2.MessageEvent.SerializeToString,
            backend__pb2.EmptyResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def getMessageEvent(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(request, target, '/chat.ChatService/getMessageEvent',
            backend__pb2.GetMessageRequest.SerializeToString,
            backend__pb2.MessageEvent.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def deleteMessageEvent(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/chat.ChatService/deleteMessageEvent',
            backend__pb2.MessageEvent.SerializeToString,
            backend__pb2.EmptyResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def notifyNewMessage(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/chat.ChatService/notifyNewMessage',
            backend__pb2.NotifyEvent.SerializeToString,
            backend__pb2.EmptyResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
