# Generated by Django 4.2.1 on 2023-05-23 20:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goods_for_people', '0002_alter_profile_birth_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chat',
            name='ad_id',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='birth_date',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='telephone',
        ),
        migrations.AlterField(
            model_name='ad',
            name='full_description',
            field=models.TextField(blank=True, max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='ad',
            name='photo',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='ad',
            name='short_description',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
