# Generated by Django 4.2.1 on 2023-05-23 23:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('goods_for_people', '0003_remove_chat_ad_id_remove_profile_birth_date_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='chat',
            old_name='user_buyer',
            new_name='user_1',
        ),
        migrations.RenameField(
            model_name='chat',
            old_name='user_seller',
            new_name='user_2',
        ),
    ]
