# Generated by Django 4.2.1 on 2023-05-24 01:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goods_for_people', '0004_rename_user_buyer_chat_user_1_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ad',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='uploads/'),
        ),
    ]
